### ISSUE TITLE
ans-three 点评

### ISSUE THREAD

**Issue by jwu** [LKeL/Learning-Report#2]
这样的答题页面我下载到本地也跑不起来, 他缺少库, 缺少使用说明的 Readme, 缺少自己对该问题解决方式的描述.

如果认真对待 Learning-Report 这个仓库, 我想你会为每一个问题建立一个 Folder, 让 review 的人, 只需要 git clone 你的 repo, 就能够在良好的运行环境中进行 review.

这些程序员的基本功请认真对待.

此外, .html 文件的 tab 请使用一个自定的规范, 我在阅读你的代码中, 发现你的 html, js 的 tab 缩进, 有时 4格, 有时 2格, 有时 8格, 有时更多, 我不能明白你的 repo 里的代码规范是怎样. 请在书写自己的代码时, 也多为读代码的人考虑.

**Comment by LKeL** [comment]
好的，回去就改
