### ISSUE TITLE
ans-six 点评

### ISSUE THREAD

**Issue by jwu** [LKeL/Learning-Report#4]
1. `{{}}` 你的回答中说这是一个动态绑定, 是否能具体说一下什么是动态绑定? 根据你的回答, 我在网上找到的关于动态绑定的定义就是可以在运行时绑定? 如果不是, 请告诉我究竟他是什么? 他最终做了什么?
2. `有的吧`, 那究竟是有还是没有? 如果有, 是否能够书写出一个样例证明? 如果没有, 说明理由.
3. 没回答重点
4. 错误
5. good

进阶中的 问题 3, 4, 5 没回答.

**Comment by LKeL** [comment]
345还有样式那的题目还没更新到这，错误回去看看改好再发上来
